# -*- coding: utf-8 -*-
##
## This file is part of Invenio.
## Copyright (C) 2013, 2014 CERN.
##
## Invenio is free software; you can redistribute it and/or
## modify it under the terms of the GNU General Public License as
## published by the Free Software Foundation; either version 2 of the
## License, or (at your option) any later version.
##
## Invenio is distributed in the hope that it will be useful, but
## WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
## General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with Invenio; if not, write to the Free Software Foundation, Inc.,
## 59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.

notifications:
  email: false

services:
  - mysql
  - rabbitmq
  - redis
  - mongodb

language: python

python:
  - "2.6"
  - "2.7"

install:
  - "sudo add-apt-repository -y ppa:chris-lea/node.js"
  - "sudo apt-get update"
  - "sudo apt-get install apache2 libapache2-mod-wsgi ssl-cert poppler-utils git subversion nodejs --fix-missing"
  - "sudo su -c \"npm install -g bower grunt-cli\""
  - "npm install"
  - "bower install"
  - "sudo a2enmod actions"
  - "sudo a2enmod version"
  - "sudo a2enmod rewrite"
  - "sudo mkdir /etc/apache2/ssl"
  - "sudo /usr/sbin/make-ssl-cert /usr/share/ssl-cert/ssleay.cnf /etc/apache2/ssl/apache.pem"
  - "travis_retry pip install . --process-dependency-links --allow-all-external"
  - "travis_retry pip install -r requirements-mongo.txt --allow-all-external"
  - "travis_retry pip install -r requirements-img.txt"
  - "travis_retry pip install -r requirements-extras.txt"
  - "pybabel compile -f -d invenio/base/translations/"
  - "inveniomanage config create secret-key"
  - "inveniomanage config set CFG_EMAIL_BACKEND flask.ext.email.backends.console.Mail"
  - "inveniomanage config set CFG_BIBSCHED_PROCESS_USER `whoami`"
  - "inveniomanage config set PACKAGES_EXCLUDE []"  # test all packages
  - "inveniomanage config set CFG_TMPDIR /tmp"  # test all packages
  - "grunt"

before_script:
  - "inveniomanage apache create-config"
  - "sudo ln -s $VIRTUAL_ENV/var/invenio.base-instance/apache/invenio-apache-vhost.conf /etc/apache2/sites-enabled/invenio.conf"
  - "sudo ln -s $VIRTUAL_ENV/var/invenio.base-instance/apache/invenio-apache-vhost-ssl.conf /etc/apache2/sites-enabled/invenio-ssl.conf"
  - "sudo /usr/sbin/a2dissite default || echo ':('"
#  - "sudo /usr/sbin/a2ensite invenio || echo ':('" # enable Invenio web site
#  - "sudo /usr/sbin/a2ensite invenio-ssl || echo ':('" # enable Invenio secure web site
  - "sudo /usr/sbin/a2enmod ssl" # enable SSL module
  - "sudo /usr/sbin/a2enmod xsendfile || echo ':('"
  - "sudo apachectl configtest && sudo service apache2 restart || echo 'Apache failed ...'"
  - "inveniomanage database init --yes-i-know || echo ':('"
  - "inveniomanage database create || echo ':('"
#  - "inveniomanage demosite create"
#  - "inveniomanage demosite populate"

script:
  - "python setup.py test"
#  - "wget -O /dev/null http://localhost"
