# -*- coding: utf-8 -*-
##
## This file is part of Invenio.
## Copyright (C) 2013, 2014, 2016 CERN.
##
## Invenio is free software; you can redistribute it and/or
## modify it under the terms of the GNU General Public License as
## published by the Free Software Foundation; either version 2 of the
## License, or (at your option) any later version.
##
## Invenio is distributed in the hope that it will be useful, but
## WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
## General Public License for more details.
##
## You should have received a copy of the GNU General Public License
## along with Invenio; if not, write to the Free Software Foundation, Inc.,
## 59 Temple Place, Suite 330, Boston, MA 02111-1307, USA.

notifications:
  email: false

sudo: true

python:
  - "2.6"

env:
  global:
    - INVENIO_SRCDIR=$(pwd)
    - INVENIO_ADMIN_EMAIL=info@inveniosoftware.org
    - INVENIO_WEB_DSTDIR=/opt/invenio
    - INVENIO_WEB_HOST=127.0.0.1
    - INVENIO_WEB_USER=www-data
    - INVENIO_WEB_SMTP_PORT=0
    - INVENIO_MYSQL_HOST=127.0.0.1
    - INVENIO_MYSQL_DBNAME=invenio1
    - INVENIO_MYSQL_DBUSER=invenio1
    - INVENIO_MYSQL_DBPASS=dbpass123

install:
  - ./scripts/provision-mysql.sh
  - ./scripts/provision-web.sh
  - ./scripts/create-instance.sh
  - ./scripts/populate-instance.sh

script:
  - sudo -u www-data nosetests /opt/invenio/lib/python/invenio/*_unit_tests.py
  - sudo -u www-data nosetests /opt/invenio/lib/python/invenio/*_regression_tests.py
